### ISSUE TITLE
Code Standard conversion to MarkDown from Wiki

### ISSUE THREAD

**Issue by Johnny2136** [CA-CST-SII/Software-Standards#8]
Converted the wiki files to .md extensions. Completed reformatting of Java and General Agnostic Standards. Updating intro page as I complete reformating.

**Comment by mjmeccia** [comment]
Thanks Johnny. Have a good w/e

Mike

**Comment by Johnny2136** [comment]
Added PHP Codeing standards and PHP Documentation guide.
